"""Product-authored, layperson guidance for official NIST CSF 2.0 outcomes.

This is deliberately separate from the vendored NIST catalog.  It explains
what an outcome means for one Windows PC; it is not NIST text or a claim of
CSF compliance.
"""

_ALL_DRAFT_GUIDANCE_EN_US = {
    "GV.OC-01": "Know what this PC is used for and which work, records, or services depend on it.",
    "GV.OC-02": "Consider who relies on this PC and what security expectations they have.",
    "GV.OC-03": "Identify the privacy, contract, or legal rules that affect data and work on this PC.",
    "GV.OC-04": "Identify the important work this PC supports and who would be affected if it stopped.",
    "GV.OC-05": "List the services, accounts, software, and connections this PC needs to do its job.",
    "GV.OV-01": "Periodically review whether this PC's security approach still matches its real risks.",
    "GV.OV-02": "Adjust this PC's security priorities when its work, data, software, or threats change.",
    "GV.OV-03": "Check whether the protections and monitoring on this PC are working as intended.",
    "GV.PO-01": "Set practical rules for safely using, maintaining, and protecting this PC.",
    "GV.PO-02": "Revisit this PC's security rules when software, threats, requirements, or its use changes.",
    "GV.RM-01": "Decide which security outcomes matter most for this PC and the work it supports.",
    "GV.RM-02": "Decide which risks on this PC are acceptable and which need action.",
    "GV.RM-03": "Include PC security risks when making everyday business and technology decisions.",
    "GV.RM-04": "Decide in advance whether to reduce, avoid, transfer, or knowingly accept a PC risk.",
    "GV.RM-05": "Know who to contact when this PC's security could affect customers, vendors, or support providers.",
    "GV.RM-06": "Use a consistent, understandable way to compare and prioritize security risks on this PC.",
    "GV.RM-07": "Consider security improvements that can also make this PC and its work more reliable.",
    "GV.RR-01": "Make one person accountable for security decisions affecting this PC.",
    "GV.RR-02": "Make clear who may administer, use, support, and approve changes to this PC.",
    "GV.RR-03": "Set aside enough time, tools, and support to keep this PC safely maintained.",
    "GV.RR-04": "Include safe PC setup, access changes, and offboarding in everyday people practices.",
    "GV.SC-01": "Set simple rules for managing security risks from products and services used by this PC.",
    "GV.SC-02": "Know which vendors or support providers can affect this PC and what each is responsible for.",
    "GV.SC-03": "Consider supplier and service-provider risks when assessing this PC's overall security.",
    "GV.SC-04": "Know which vendors and services are most important to this PC's work.",
    "GV.SC-05": "Set security expectations when buying software, support, cloud services, or hardware for this PC.",
    "GV.SC-06": "Check a vendor or product before trusting it with this PC or its data.",
    "GV.SC-07": "Keep watch for security risks in the vendors, products, and services this PC depends on.",
    "GV.SC-08": "Include key vendors and support contacts in this PC's incident and recovery planning.",
    "GV.SC-09": "Review whether suppliers continue to follow the security practices this PC depends on.",
    "GV.SC-10": "Plan how to remove access and protect data when a vendor or service relationship ends.",
    "ID.AM-01": "Keep an up-to-date list of the computer, attached devices, and hardware you manage.",
    "ID.AM-02": "Know what software, services, and accounts are installed or used on this PC.",
    "ID.AM-03": "Understand how this PC connects to the internet, local network, and important services.",
    "ID.AM-04": "Keep track of outside services this PC relies on, such as backup, email, or remote support.",
    "ID.AM-05": "Identify which data, software, and functions on this PC matter most if disrupted.",
    "ID.AM-06": "Know who is responsible for using, maintaining, and securing this PC.",
    "ID.AM-07": "Know what important data this PC stores and where it is kept.",
    "ID.AM-08": "Manage this PC, its software, and its data from setup through replacement or disposal.",
    "ID.BE-01": "Understand how this PC supports the products, services, or work you provide to others.",
    "ID.BE-02": "Recognize any industry or public-service role that makes this PC especially important.",
    "ID.BE-03": "Decide which work on this PC must be protected and restored first.",
    "ID.BE-04": "Identify the people, services, and technology this PC depends on to do important work.",
    "ID.BE-05": "Define how quickly this PC must keep working or recover after a disruption.",
    "ID.GV-01": "Document and share the basic security rules for this PC.",
    "ID.GV-02": "Coordinate PC security responsibilities with owners, staff, and outside support.",
    "ID.GV-03": "Understand the privacy and legal obligations that apply to this PC's data and use.",
    "ID.GV-04": "Use a repeatable process to identify, decide on, and track PC security risks.",
    "ID.IM-01": "Use reviews of this PC to identify practical security improvements.",
    "ID.IM-02": "Use tests and practice exercises to find ways to improve this PC's security.",
    "ID.IM-03": "Learn from routine PC problems, changes, and maintenance work.",
    "ID.IM-04": "Keep this PC's incident and recovery plans current and easy to use.",
    "ID.RA-01": "Identify and record weaknesses in this PC, its software, and its settings.",
    "ID.RA-02": "Use trustworthy threat information to understand risks that may affect this PC.",
    "ID.RA-03": "Identify likely threats to this PC from attackers, mistakes, failures, or outside services.",
    "ID.RA-04": "Estimate how likely a problem is and how much it could affect this PC and its work.",
    "ID.RA-05": "Use known threats and weaknesses to decide which PC risks need attention first.",
    "ID.RA-06": "Choose, record, and follow through on the best response for each important PC risk.",
    "ID.RA-07": "Review and record the security impact of important PC changes and exceptions.",
    "ID.RA-08": "Have a way to receive and act on reports of weaknesses in software or services you use.",
    "ID.RA-09": "Check that new hardware and software come from trustworthy sources before using them.",
    "ID.RA-10": "Assess important technology suppliers before relying on their products or services.",
    "ID.RM-01": "Use an agreed process for managing the security risks of this PC.",
    "ID.RM-02": "State clearly which risks to this PC are acceptable and which are not.",
    "ID.RM-03": "Set PC risk tolerance with the importance of your work and industry in mind.",
    "ID.SC-01": "Use a process to manage security risks from suppliers and services used by this PC.",
    "ID.SC-02": "Identify and assess vendors and third parties that can affect this PC or its data.",
    "ID.SC-03": "Use purchase terms and service agreements to set security expectations for providers.",
    "ID.SC-04": "Periodically check whether important providers meet their security commitments.",
    "ID.SC-05": "Include key providers in plans for responding to and recovering from a PC incident.",
    "PR.AA-01": "Know which people, services, and devices have identities or credentials for this PC.",
    "PR.AA-02": "Confirm that each account belongs to a known person or a legitimate PC function.",
    "PR.AA-03": "Require appropriate sign-in checks for people, services, and devices that use this PC.",
    "PR.AA-04": "Use this only when the PC relies on trusted sign-in information from another identity service.",
    "PR.AA-05": "Limit each account to the access it needs, especially administrator and remote access.",
    "PR.AA-06": "Use locks, screen timeout, encryption, and physical safeguards appropriate for this PC's location.",
    "PR.AC-01": "Create, review, and remove accounts and credentials in a controlled way.",
    "PR.AC-02": "Protect the PC and its storage from unauthorized physical access.",
    "PR.AC-03": "Allow remote access only when it is needed, configured safely, and reviewed.",
    "PR.AC-04": "Give each person and service only the permissions needed for its role.",
    "PR.AC-05": "Protect this PC's network connections from unwanted access between networks or devices.",
    "PR.AC-06": "Verify that sign-in identities are linked to the right people or services.",
    "PR.AC-07": "Use sign-in protection that matches the sensitivity of the PC and the work being done.",
    "PR.AT-01": "Make sure everyone using this PC understands basic safe computing practices.",
    "PR.AT-02": "Give people with PC administration or security duties the training their role needs.",
    "PR.AT-03": "Make sure outside support and service providers understand their security responsibilities.",
    "PR.AT-04": "Ensure the business owner understands their responsibilities for this PC's security.",
    "PR.AT-05": "Ensure people responsible for physical or cybersecurity protection know their duties.",
    "PR.DS-01": "Protect files stored on this PC from unauthorized viewing, change, loss, or damage.",
    "PR.DS-02": "Protect important data while this PC sends or receives it over a network.",
    "PR.DS-03": "Remove or transfer this PC, its drives, and its data safely when they are no longer needed.",
    "PR.DS-04": "Keep enough storage and computing capacity for this PC to work reliably.",
    "PR.DS-05": "Use safeguards that reduce the chance of sensitive data leaving this PC improperly.",
    "PR.DS-06": "Check that software, firmware, and important data have not been changed unexpectedly.",
    "PR.DS-07": "Keep testing or development work separate from the PC environment used for real work.",
    "PR.DS-08": "Check hardware integrity when a device or component may have been altered or replaced.",
    "PR.DS-10": "Protect sensitive data while it is open and being used on this PC.",
    "PR.DS-11": "Create, protect, and test backups so important PC data can be restored.",
    "PR.IP-01": "Keep a known, secure baseline for this PC's important settings and installed components.",
    "PR.IP-02": "Use a safe, repeatable process when developing or making major changes to this PC.",
    "PR.IP-03": "Review, approve, and record important configuration changes before or as they are made.",
    "PR.IP-04": "Back up important PC information and verify that it can be restored.",
    "PR.IP-05": "Meet physical-environment rules that protect this PC from theft, damage, or unsafe conditions.",
    "PR.IP-06": "Destroy data on this PC safely when policy, privacy, or business needs require it.",
    "PR.IP-07": "Improve PC protection processes when reviews, incidents, or changes show a need.",
    "PR.IP-08": "Share what you learn about which PC protections work well or need improvement.",
    "PR.IP-09": "Keep practical response and recovery plans for serious problems affecting this PC.",
    "PR.IP-10": "Practice this PC's response and recovery steps before an emergency happens.",
    "PR.IP-11": "Include account removal, access changes, and screening in people-related PC security steps.",
    "PR.IP-12": "Use a planned process to find, prioritize, and fix software weaknesses on this PC.",
    "PR.IR-01": "Protect this PC and its network access from unauthorized use.",
    "PR.IR-02": "Protect this PC from power, temperature, water, fire, and other environmental problems.",
    "PR.IR-03": "Prepare this PC to keep essential work going during failures or attacks.",
    "PR.IR-04": "Maintain enough computing, storage, and connection capacity for reliable PC use.",
    "PR.MA-01": "Perform and record PC maintenance using approved people, tools, and methods.",
    "PR.MA-02": "Control and record remote maintenance so it does not create unauthorized access.",
    "PR.PS-01": "Use consistent, secure practices when changing this PC's settings or software.",
    "PR.PS-02": "Keep software updated, replace unsupported software, and remove software no longer needed.",
    "PR.PS-03": "Maintain, replace, and dispose of PC hardware according to its importance and risk.",
    "PR.PS-04": "Keep useful system records so important PC activity can be monitored and reviewed.",
    "PR.PS-05": "Prevent unapproved software from being installed or run on this PC.",
    "PR.PS-06": "Use secure practices when this PC is used to develop or test software.",
    "PR.PT-01": "Decide which PC activity should be logged and review those records when needed.",
    "PR.PT-02": "Protect USB drives and other removable media used with this PC.",
    "PR.PT-03": "Turn off or remove PC features and services that are not needed.",
    "PR.PT-04": "Protect the networks and connections this PC uses for communication and control.",
    "PR.PT-05": "Use practical resilience measures so this PC can keep working through expected failures.",
    "DE.AE-01": "Know what normal network activity looks like for this PC so unusual activity stands out.",
    "DE.AE-02": "Review suspicious activity to understand what happened and whether it matters.",
    "DE.AE-03": "Compare information from more than one source before deciding what a PC event means.",
    "DE.AE-04": "Estimate how far a suspicious event reaches and what it could affect.",
    "DE.AE-05": "Set sensible thresholds for when this PC should raise an alert for review.",
    "DE.AE-06": "Make sure relevant people and tools receive important PC event information.",
    "DE.AE-07": "Use threat information to put suspicious PC activity in context.",
    "DE.AE-08": "Decide when evidence is serious enough to treat a PC event as an incident.",
    "DE.CM-01": "Monitor this PC's network connections and services for signs of unwanted activity.",
    "DE.CM-02": "Use practical physical checks when this PC's location creates security risks.",
    "DE.CM-03": "Watch relevant PC use for activity that may be unsafe or unauthorized.",
    "DE.CM-04": "Use trusted protections to look for malicious software on this PC.",
    "DE.CM-05": "Watch for unapproved scripts or code that could run on this PC.",
    "DE.CM-06": "Monitor important outside services used by this PC for security problems.",
    "DE.CM-07": "Look for unauthorized users, connections, devices, software, or changes on this PC.",
    "DE.CM-08": "Run appropriate checks to find known weaknesses in this PC and its software.",
    "DE.CM-09": "Monitor this PC's hardware, software, and data for unexpected or risky changes.",
    "DE.DP-01": "Make clear who is responsible for monitoring and reviewing PC security signals.",
    "DE.DP-02": "Perform PC monitoring in a way that respects privacy, legal, and business requirements.",
    "DE.DP-03": "Test PC monitoring so you know it can detect the events you care about.",
    "DE.DP-04": "Share useful PC monitoring results with the people who need to act on them.",
    "DE.DP-05": "Improve PC monitoring when reviews, incidents, or new risks show a need.",
    "RS.AN-01": "Investigate important PC alerts instead of assuming every alert is a confirmed incident.",
    "RS.AN-02": "Understand what an incident could affect on this PC and in the work it supports.",
    "RS.AN-03": "Determine what happened, how it happened, and what caused a PC incident.",
    "RS.AN-04": "Classify a PC incident consistently so the right response can be chosen.",
    "RS.AN-05": "Receive, assess, and act on reports of weaknesses affecting this PC.",
    "RS.AN-06": "Keep trustworthy records of actions taken while investigating a PC incident.",
    "RS.AN-07": "Collect incident evidence carefully so it remains reliable and traceable.",
    "RS.AN-08": "Estimate and confirm how serious and widespread a PC incident is.",
    "RS.CO-01": "Know who does what first when this PC needs a security response.",
    "RS.CO-02": "Notify the right people and providers when a PC incident affects them.",
    "RS.CO-03": "Share accurate incident information with people who need it to respond.",
    "RS.CO-04": "Coordinate the PC response with owners, support providers, and affected parties.",
    "RS.CO-05": "Share useful threat information externally when it is safe and appropriate.",
    "RS.IM-01": "Use lessons from a PC incident to improve the response plan.",
    "RS.IM-02": "Update response choices when experience shows a better way to handle PC incidents.",
    "RS.MA-01": "Follow the PC response plan and involve needed providers after an incident is declared.",
    "RS.MA-02": "Review incoming PC incident reports to confirm they are real and need action.",
    "RS.MA-03": "Sort PC incidents by type and urgency so the most important are handled first.",
    "RS.MA-04": "Escalate a PC incident when it exceeds the authority or resources available locally.",
    "RS.MA-05": "Use clear criteria to decide when a PC incident should move into recovery.",
    "RS.MI-01": "Limit a PC incident so it cannot cause further harm.",
    "RS.MI-02": "Remove the cause of a PC incident before returning to normal use.",
    "RS.MI-03": "Fix newly found weaknesses or record an informed decision to accept the risk.",
    "RS.RP-01": "Follow the PC response plan during and after a security incident.",
    "RC.CO-01": "Manage public or customer communications carefully after a PC incident.",
    "RC.CO-02": "Take appropriate steps to rebuild trust after an incident affects this PC's work.",
    "RC.CO-03": "Keep affected people informed about progress restoring this PC's important capabilities.",
    "RC.CO-04": "Use approved, accurate messages for public updates about recovery when needed.",
    "RC.IM-01": "Use recovery lessons to improve how this PC is restored after future incidents.",
    "RC.IM-02": "Update recovery choices when experience shows a better way to restore this PC.",
    "RC.RP-01": "Begin the PC recovery plan when incident response says recovery should start.",
    "RC.RP-02": "Choose and prioritize the recovery steps that restore the most important PC work first.",
    "RC.RP-03": "Check backups and recovery media before using them to restore this PC.",
    "RC.RP-04": "Use important work and acceptable risk to decide what normal operation means after recovery.",
    "RC.RP-05": "Verify that restored files, software, and services are trustworthy before normal use resumes.",
    "RC.RP-06": "Formally close recovery only after the PC is stable and the incident record is complete.",
}


def _active_official_subcategory_ids() -> set[str]:
    from csf_catalog import load_official_catalog

    return {
        subcategory["id"]
        for function in load_official_catalog()["functions"]
        for category in function["categories"]
        for subcategory in category["subcategories"]
    }


_ACTIVE_OFFICIAL_SUBCATEGORY_IDS = _active_official_subcategory_ids()
_MISSING_ACTIVE_GUIDANCE = _ACTIVE_OFFICIAL_SUBCATEGORY_IDS.difference(_ALL_DRAFT_GUIDANCE_EN_US)
if _MISSING_ACTIVE_GUIDANCE:
    raise ValueError(f"Plain-English guidance is missing active CSF Subcategories: {sorted(_MISSING_ACTIVE_GUIDANCE)}")

# The shipped set intentionally excludes withdrawn historical OSCAL controls.
PLAIN_ENGLISH_GUIDANCE_EN_US = {
    identifier: _ALL_DRAFT_GUIDANCE_EN_US[identifier]
    for identifier in sorted(_ACTIVE_OFFICIAL_SUBCATEGORY_IDS)
}
