"""Product-authored information-flow relationships between CSF 2.0 outcomes.

The CSF Core defines outcomes, not a required implementation order.  This
catalog records a deliberately limited set of planning relationships for the
product: information an outcome can make available and downstream outcomes
that use that information.  It is not an official NIST dependency map and it
does not require a user to implement a particular control or follow one fixed
sequence.
"""

from typing import Dict, List


INFORMATION_ITEMS: List[Dict[str, str]] = [
    {
        "information_id": "organizational_mission",
        "title": "Organizational mission and objectives",
        "description": "What the organization is trying to accomplish and which objectives cybersecurity decisions must support.",
    },
    {
        "information_id": "stakeholder_cybersecurity_needs",
        "title": "Stakeholder cybersecurity and privacy needs",
        "description": "The needs and expectations of people and organizations affected by cybersecurity decisions.",
    },
    {
        "information_id": "legal_contractual_requirements",
        "title": "Legal, regulatory, and contractual requirements",
        "description": "Applicable cybersecurity, privacy, and agreement requirements that constrain decisions and communications.",
    },
    {
        "information_id": "critical_services_and_objectives",
        "title": "Critical services and objectives",
        "description": "Services, capabilities, and objectives that others depend on, including their expected resilience.",
    },
    {
        "information_id": "external_dependencies",
        "title": "External dependencies",
        "description": "External products, services, facilities, and providers needed to support important work.",
    },
    {
        "information_id": "risk_objectives_and_tolerance",
        "title": "Risk objectives, tolerance, and response direction",
        "description": "The organization's agreed objectives, acceptable risk boundaries, and response options.",
    },
    {
        "information_id": "risk_assessment_method",
        "title": "Risk assessment method",
        "description": "The common method used to calculate, document, categorize, and prioritize cybersecurity risk.",
    },
    {
        "information_id": "cybersecurity_roles",
        "title": "Cybersecurity roles and authorities",
        "description": "Who is responsible for decisions, implementation, review, escalation, and communication.",
    },
    {
        "information_id": "supplier_criticality",
        "title": "Supplier criticality and priority",
        "description": "Which suppliers and providers are important enough to require deeper review, requirements, or monitoring.",
    },
    {
        "information_id": "asset_inventory",
        "title": "Asset inventory",
        "description": "Known hardware, software, systems, services, and data managed by the organization.",
    },
    {
        "information_id": "network_and_data_flows",
        "title": "Network communication and data flows",
        "description": "How authorized systems communicate and where information moves internally and externally.",
    },
    {
        "information_id": "asset_criticality",
        "title": "Asset criticality and impact",
        "description": "The relative importance of assets based on mission, resources, classification, and likely impact.",
    },
    {
        "information_id": "vulnerabilities_and_threats",
        "title": "Validated vulnerabilities and relevant threats",
        "description": "Known weaknesses and internal or external threats that could affect the organization.",
    },
    {
        "information_id": "risk_scenarios_and_priorities",
        "title": "Risk scenarios and priorities",
        "description": "Recorded likelihoods, impacts, inherent risk, and the order in which risks should be addressed.",
    },
    {
        "information_id": "selected_risk_responses",
        "title": "Selected risk responses",
        "description": "Chosen, planned, tracked, and communicated actions for addressing prioritized risk.",
    },
    {
        "information_id": "change_and_exception_risk_records",
        "title": "Change and exception risk records",
        "description": "Documented risk impacts, approvals, exceptions, planned responses, and tracking information for proposed changes and exceptions.",
    },
    {
        "information_id": "secure_development_performance_results",
        "title": "Secure development performance results",
        "description": "Recorded results from monitoring secure software development practices throughout the software development life cycle.",
    },
    {
        "information_id": "authorized_adverse_event_alerts",
        "title": "Authorized adverse-event alerts",
        "description": "Adverse-event alerts, log-analysis findings, and tickets delivered to authorized staff and tools for review and response.",
    },
    {
        "information_id": "monitoring_findings",
        "title": "Monitoring findings and potentially adverse events",
        "description": "Signals from monitored environments, systems, providers, and personnel activity that need analysis.",
    },
    {
        "information_id": "incident_analysis",
        "title": "Incident analysis and response status",
        "description": "What happened, its scope and impact, the investigation record, and the current response status.",
    },
    {
        "information_id": "recovery_priorities_and_status",
        "title": "Recovery priorities and restoration status",
        "description": "What must be restored first, the integrity checks required, and progress toward normal operation.",
    },
    {
        "information_id": "improvement_lessons",
        "title": "Lessons and improvement opportunities",
        "description": "Findings from evaluations, exercises, operations, incidents, and recovery that should improve future work.",
    },
    {
        "information_id": "supplier_requirements_and_agreements",
        "title": "Supplier requirements and agreements",
        "description": "Documented cybersecurity requirements, responsibilities, and agreement terms for suppliers and other third parties.",
    },
    {
        "information_id": "supply_chain_program_direction",
        "title": "Supply-chain program direction",
        "description": "The agreed supply-chain risk strategy, objectives, policies, and processes that guide supplier work.",
    },
    {
        "information_id": "supplier_lifecycle_results",
        "title": "Supplier lifecycle results",
        "description": "Recorded supplier risk, assessment, response, and monitoring results over the relationship lifecycle.",
    },
    {
        "information_id": "threat_intelligence",
        "title": "Threat intelligence",
        "description": "Relevant internal and external threat information received from sharing forums and other sources.",
    },
    {
        "information_id": "restoration_assets",
        "title": "Restoration assets",
        "description": "Backups and other assets maintained for restoring systems, services, and data.",
    },
    {
        "information_id": "verified_restoration_assets",
        "title": "Verified restoration assets",
        "description": "Backups and restoration assets whose integrity has been checked before restoration use.",
    },
    {
        "information_id": "log_records",
        "title": "Log records",
        "description": "Generated logs that support continuous monitoring, investigation, and evidence preservation.",
    },
    {
        "information_id": "event_threat_context",
        "title": "Event threat context",
        "description": "Threat intelligence and contextual information applied when analyzing potentially adverse events.",
    },
    {
        "information_id": "analyzed_event_information",
        "title": "Analyzed event information",
        "description": "Analyzed potentially adverse events, including the associated activity, impact, scope, and incident decision.",
    },
    {
        "information_id": "triaged_incident_reports",
        "title": "Triaged incident reports",
        "description": "Incident reports that have been received, validated, and prepared for categorization and prioritization.",
    },
    {
        "information_id": "incident_priority_and_scope",
        "title": "Incident priority and scope",
        "description": "The categorized incident priority and validated magnitude, scope, and impact needed for escalation or recovery decisions.",
    },
    {
        "information_id": "recovery_initiation_decision",
        "title": "Recovery initiation decision",
        "description": "The decision and criteria that initiate the recovery portion of the incident response process.",
    },
    {
        "information_id": "preserved_investigation_records",
        "title": "Preserved investigation records",
        "description": "Investigation actions and records whose integrity and provenance have been preserved.",
    },
    {
        "information_id": "external_vulnerability_disclosures",
        "title": "External vulnerability disclosures",
        "description": "Vulnerability reports received from external reporters, vendors, researchers, or disclosure channels.",
    },
    {
        "information_id": "incident_response_plan",
        "title": "Incident response plan",
        "description": "The plan and coordination arrangements used to respond to a declared incident with relevant third parties.",
    },
    {
        "information_id": "risk_management_measures_and_results",
        "title": "Risk-management measures and thresholds",
        "description": "The agreed KPIs, KRIs, and thresholds used to judge cybersecurity risk-management performance.",
    },
    {
        "information_id": "external_legal_contractual_sources",
        "title": "External legal, regulatory, and contractual sources",
        "description": "Applicable laws, regulations, contracts, privacy obligations, and other external requirements that the organization must identify and manage.",
    },
    {
        "information_id": "risk_management_performance_results",
        "title": "Risk-management performance results",
        "description": "Actual measurements, assessment results, monitoring findings, action status, supplier results, and incident results used to evaluate cybersecurity risk management.",
    },
    {
        "information_id": "risk_management_review_findings",
        "title": "Risk-management review findings",
        "description": "Performance-review findings and recommended adjustments to cybersecurity risk-management strategy, direction, or policy.",
    },
    {
        "information_id": "integrated_supply_chain_risk_records",
        "title": "Integrated supply-chain risk records",
        "description": "Material supplier and supply-chain risk information, including integrated control considerations, prepared for enterprise risk management.",
    },
]


# An outcome may be a source, but the same information can also come from
# equivalent existing records or a custom action.  ``source_guidance`` keeps
# that flexibility explicit for future UI and workflow work.
INFORMATION_SOURCES: List[Dict[str, str]] = [
    {"information_id": "organizational_mission", "source_subcategory_id": "GV.OC-01", "source_guidance": "A current mission statement, service strategy, or equivalent record may provide this information."},
    {"information_id": "stakeholder_cybersecurity_needs", "source_subcategory_id": "GV.OC-02", "source_guidance": "A stakeholder record, consultation, existing policy record, or custom action may provide this information."},
    {"information_id": "legal_contractual_requirements", "source_subcategory_id": "GV.OC-03", "source_guidance": "A legal, privacy, contractual, or compliance record may provide this information."},
    {"information_id": "critical_services_and_objectives", "source_subcategory_id": "GV.OC-04", "source_guidance": "A business-impact, service-level, or continuity record may provide this information."},
    {"information_id": "external_dependencies", "source_subcategory_id": "GV.OC-05", "source_guidance": "A supplier, service, facility, or dependency inventory may provide this information."},
    {"information_id": "risk_objectives_and_tolerance", "source_subcategory_id": "GV.RM-01", "source_guidance": "Risk objectives may be combined with tolerance and response-direction records."},
    {"information_id": "risk_objectives_and_tolerance", "source_subcategory_id": "GV.RM-02", "source_guidance": "Risk tolerance may be combined with objectives and response-direction records."},
    {"information_id": "risk_objectives_and_tolerance", "source_subcategory_id": "GV.RM-04", "source_guidance": "Risk response direction may be combined with objectives and tolerance records."},
    {"information_id": "risk_assessment_method", "source_subcategory_id": "GV.RM-06", "source_guidance": "An established risk assessment method or equivalent documented process may provide this information."},
    {"information_id": "cybersecurity_roles", "source_subcategory_id": "GV.RR-02", "source_guidance": "A responsibility assignment, policy, or owner record may provide this information."},
    {"information_id": "supplier_criticality", "source_subcategory_id": "GV.SC-04", "source_guidance": "A supplier inventory, criticality assessment, or dependency record may provide this information."},
    {"information_id": "asset_inventory", "source_subcategory_id": "ID.AM-01", "source_guidance": "A managed hardware inventory may provide this information."},
    {"information_id": "asset_inventory", "source_subcategory_id": "ID.AM-02", "source_guidance": "A managed software, service, or system inventory may provide this information."},
    {"information_id": "asset_inventory", "source_subcategory_id": "ID.AM-04", "source_guidance": "A supplier-service inventory may provide this information."},
    {"information_id": "asset_inventory", "source_subcategory_id": "ID.AM-07", "source_guidance": "A designated-data inventory may provide this information."},
    {"information_id": "network_and_data_flows", "source_subcategory_id": "ID.AM-03", "source_guidance": "A current network diagram, authorized communication record, or data-flow record may provide this information."},
    {"information_id": "asset_criticality", "source_subcategory_id": "ID.AM-05", "source_guidance": "An asset classification, business-impact, or mission-impact record may provide this information."},
    {"information_id": "vulnerabilities_and_threats", "source_subcategory_id": "ID.RA-01", "source_guidance": "Validated vulnerability records may provide this information."},
    {"information_id": "vulnerabilities_and_threats", "source_subcategory_id": "ID.RA-03", "source_guidance": "Threat records or current threat intelligence may provide this information."},
    {"information_id": "risk_scenarios_and_priorities", "source_subcategory_id": "ID.RA-04", "source_guidance": "Recorded likelihood and impact analysis may provide this information."},
    {"information_id": "risk_scenarios_and_priorities", "source_subcategory_id": "ID.RA-05", "source_guidance": "A risk register or prioritization record may provide this information."},
    {"information_id": "selected_risk_responses", "source_subcategory_id": "ID.RA-06", "source_guidance": "A recorded treatment decision, action plan, or accepted-risk record may provide this information."},
    {"information_id": "change_and_exception_risk_records", "source_subcategory_id": "ID.RA-07", "source_guidance": "Documented change and exception reviews, approvals, risk impacts, and tracking records may provide this information."},
    {"information_id": "secure_development_performance_results", "source_subcategory_id": "PR.PS-06", "source_guidance": "Monitoring records for secure software development practices throughout the life cycle may provide this information."},
    {"information_id": "authorized_adverse_event_alerts", "source_subcategory_id": "DE.AE-06", "source_guidance": "Authorized staff and tools may receive adverse-event alerts, log-analysis findings, and tickets through this distribution process."},
    {"information_id": "monitoring_findings", "source_subcategory_id": "DE.CM-01", "source_guidance": "Monitoring records may provide this information."},
    {"information_id": "monitoring_findings", "source_subcategory_id": "DE.CM-03", "source_guidance": "Personnel activity and technology-usage monitoring may provide this information."},
    {"information_id": "monitoring_findings", "source_subcategory_id": "DE.CM-06", "source_guidance": "External-provider monitoring may provide this information."},
    {"information_id": "monitoring_findings", "source_subcategory_id": "DE.CM-09", "source_guidance": "Hardware, software, runtime, and data monitoring may provide this information."},
    {"information_id": "incident_analysis", "source_subcategory_id": "DE.AE-08", "source_guidance": "An incident declaration and related analysis records may provide this information."},
    {"information_id": "incident_analysis", "source_subcategory_id": "RS.AN-03", "source_guidance": "Incident investigation and root-cause analysis may provide this information."},
    {"information_id": "incident_analysis", "source_subcategory_id": "RS.AN-08", "source_guidance": "Incident magnitude and scope analysis may provide this information."},
    {"information_id": "recovery_priorities_and_status", "source_subcategory_id": "RC.RP-02", "source_guidance": "Recovery action selection and progress records may provide this information."},
    {"information_id": "recovery_priorities_and_status", "source_subcategory_id": "RC.RP-05", "source_guidance": "Restoration verification and normal-operation confirmation may provide this information."},
    {"information_id": "improvement_lessons", "source_subcategory_id": "ID.IM-01", "source_guidance": "Evaluation findings may provide this information."},
    {"information_id": "improvement_lessons", "source_subcategory_id": "ID.IM-02", "source_guidance": "Test and exercise findings may provide this information."},
    {"information_id": "improvement_lessons", "source_subcategory_id": "ID.IM-03", "source_guidance": "Operational and incident lessons may provide this information."},
    {"information_id": "supplier_requirements_and_agreements", "source_subcategory_id": "GV.SC-05", "source_guidance": "Supplier cybersecurity requirements, contracts, and equivalent agreement records may provide this information."},
    {"information_id": "supply_chain_program_direction", "source_subcategory_id": "GV.SC-01", "source_guidance": "The approved supply-chain risk management program or equivalent strategy record may provide this information."},
    {"information_id": "supplier_lifecycle_results", "source_subcategory_id": "GV.SC-07", "source_guidance": "Supplier risk, assessment, response, and monitoring records may provide this information."},
    {"information_id": "threat_intelligence", "source_subcategory_id": "ID.RA-02", "source_guidance": "Threat intelligence received from sharing forums and other sources may provide this information."},
    {"information_id": "restoration_assets", "source_subcategory_id": "PR.DS-11", "source_guidance": "Maintained backups and other restoration assets may provide this information."},
    {"information_id": "verified_restoration_assets", "source_subcategory_id": "RC.RP-03", "source_guidance": "Verified backups and restoration assets may provide this information."},
    {"information_id": "log_records", "source_subcategory_id": "PR.PS-04", "source_guidance": "Generated log records may provide this information."},
    {"information_id": "event_threat_context", "source_subcategory_id": "DE.AE-07", "source_guidance": "Threat intelligence and other contextual information integrated into analysis may provide this information."},
    {"information_id": "analyzed_event_information", "source_subcategory_id": "DE.AE-02", "source_guidance": "Analysis of potentially adverse events may provide this information."},
    {"information_id": "analyzed_event_information", "source_subcategory_id": "DE.AE-04", "source_guidance": "Estimated event impact and scope may provide this information."},
    {"information_id": "analyzed_event_information", "source_subcategory_id": "DE.AE-08", "source_guidance": "An incident declaration and its supporting analysis may provide this information."},
    {"information_id": "triaged_incident_reports", "source_subcategory_id": "RS.MA-02", "source_guidance": "Validated and triaged incident reports may provide this information."},
    {"information_id": "incident_priority_and_scope", "source_subcategory_id": "RS.MA-03", "source_guidance": "Categorized and prioritized incident records may provide this information."},
    {"information_id": "incident_priority_and_scope", "source_subcategory_id": "RS.AN-08", "source_guidance": "Validated incident magnitude and scope analysis may provide this information."},
    {"information_id": "recovery_initiation_decision", "source_subcategory_id": "RS.MA-05", "source_guidance": "The applied recovery-initiation criteria and decision may provide this information."},
    {"information_id": "preserved_investigation_records", "source_subcategory_id": "RS.AN-06", "source_guidance": "Recorded investigation actions with preserved integrity and provenance may provide this information."},
    {"information_id": "external_vulnerability_disclosures", "source_subcategory_id": "External: vulnerability disclosure sources", "source_guidance": "External reporters, vendors, researchers, and disclosure channels may provide this information."},
    {"information_id": "incident_response_plan", "source_subcategory_id": "RS.MA-01", "source_guidance": "The executed incident response plan and its third-party coordination arrangements may provide this information."},
    {"information_id": "cybersecurity_roles", "source_subcategory_id": "GV.SC-02", "source_guidance": "Coordinated supplier, customer, partner, and internal cybersecurity responsibilities may provide this information."},
    {"information_id": "risk_management_measures_and_results", "source_subcategory_id": "GV.RM-01", "source_guidance": "Risk-management objectives can define the KPIs, KRIs, and thresholds used to judge whether those objectives are being achieved."},
    {"information_id": "external_legal_contractual_sources", "source_subcategory_id": "External: legal, regulatory, and contractual sources", "source_guidance": "Applicable laws, regulations, contracts, privacy obligations, and other authoritative external sources may provide this information."},
    {"information_id": "risk_management_performance_results", "source_subcategory_id": "External: operational measurement and evidence records", "source_guidance": "Monitoring, assessment, action, supplier, incident, and other operational records may provide these measured results."},
    {"information_id": "risk_management_review_findings", "source_subcategory_id": "GV.OV-03", "source_guidance": "Performance evaluation and review records may provide these findings and recommended adjustments."},
    {"information_id": "integrated_supply_chain_risk_records", "source_subcategory_id": "GV.SC-03", "source_guidance": "Integrated supply-chain risk records, material-risk escalations, and control-set considerations may provide this information."},
    {"information_id": "vulnerabilities_and_threats", "source_subcategory_id": "ID.RA-08", "source_guidance": "Validated vulnerability disclosures may provide this information."},
    {"information_id": "incident_analysis", "source_subcategory_id": "RS.AN-06", "source_guidance": "Preserved investigation records may provide this information."},
    {"information_id": "incident_analysis", "source_subcategory_id": "RS.AN-07", "source_guidance": "Collected and preserved incident data may provide this information."},
]


# ``required_input`` means that this information should be available before a
# user represents the downstream activity as complete.  ``planning_input``
# means it should be considered but an equivalent source or documented reason
# may be sufficient. ``event_input`` becomes relevant when the downstream
# incident or recovery work has been triggered.
INFORMATION_USES: List[Dict[str, str]] = [
    {"information_id": "organizational_mission", "consumer_subcategory_id": "GV.RM-01", "dependency_kind": "planning_input", "use_reason": "Set risk-management objectives that support what the organization is trying to accomplish."},
    {"information_id": "organizational_mission", "consumer_subcategory_id": "ID.AM-05", "dependency_kind": "planning_input", "use_reason": "Prioritize assets according to their effect on mission objectives."},
    {"information_id": "organizational_mission", "consumer_subcategory_id": "ID.RA-04", "dependency_kind": "planning_input", "use_reason": "Estimate impact in terms of the mission and objectives that could be affected."},
    {"information_id": "organizational_mission", "consumer_subcategory_id": "RC.RP-04", "dependency_kind": "planning_input", "use_reason": "Establish post-incident operating priorities using critical mission functions."},

    {"information_id": "stakeholder_cybersecurity_needs", "consumer_subcategory_id": "GV.RM-01", "dependency_kind": "planning_input", "use_reason": "Agree risk-management objectives that account for affected stakeholders' needs and expectations."},
    {"information_id": "stakeholder_cybersecurity_needs", "consumer_subcategory_id": "GV.RM-05", "dependency_kind": "planning_input", "use_reason": "Set communication paths that reach people who need cybersecurity risk information."},
    {"information_id": "stakeholder_cybersecurity_needs", "consumer_subcategory_id": "GV.SC-01", "dependency_kind": "planning_input", "use_reason": "Set supply-chain objectives and processes that account for relevant stakeholder needs."},
    {"information_id": "stakeholder_cybersecurity_needs", "consumer_subcategory_id": "GV.SC-05", "dependency_kind": "required_input", "use_reason": "Translate known security and privacy needs into supplier and purchasing requirements."},
    {"information_id": "stakeholder_cybersecurity_needs", "consumer_subcategory_id": "RS.CO-02", "dependency_kind": "planning_input", "use_reason": "Determine which internal and external stakeholders must be notified of an incident and what they need to know."},
    {"information_id": "stakeholder_cybersecurity_needs", "consumer_subcategory_id": "RS.CO-03", "dependency_kind": "planning_input", "use_reason": "Share incident information in a way that accounts for designated stakeholders' needs and expectations."},
    {"information_id": "stakeholder_cybersecurity_needs", "consumer_subcategory_id": "RC.CO-03", "dependency_kind": "planning_input", "use_reason": "Communicate recovery progress to stakeholders who rely on the affected capabilities or information."},

    {"information_id": "legal_contractual_requirements", "consumer_subcategory_id": "GV.PO-01", "dependency_kind": "planning_input", "use_reason": "Establish policy that reflects applicable legal, regulatory, and contractual obligations."},
    {"information_id": "legal_contractual_requirements", "consumer_subcategory_id": "GV.PO-02", "dependency_kind": "planning_input", "use_reason": "Update policy when applicable requirements change."},
    {"information_id": "legal_contractual_requirements", "consumer_subcategory_id": "GV.SC-05", "dependency_kind": "required_input", "use_reason": "Include applicable security, privacy, and contractual obligations in supplier requirements and agreements."},
    {"information_id": "legal_contractual_requirements", "consumer_subcategory_id": "RS.CO-02", "dependency_kind": "planning_input", "use_reason": "Determine notification duties and deadlines during incident response."},
    {"information_id": "legal_contractual_requirements", "consumer_subcategory_id": "RC.CO-04", "dependency_kind": "planning_input", "use_reason": "Use approved methods and messaging that meet applicable public-update requirements."},

    {"information_id": "critical_services_and_objectives", "consumer_subcategory_id": "ID.AM-05", "dependency_kind": "planning_input", "use_reason": "Prioritize assets by their importance to services and objectives that others rely on."},
    {"information_id": "critical_services_and_objectives", "consumer_subcategory_id": "ID.RA-04", "dependency_kind": "planning_input", "use_reason": "Estimate the impact of a threat scenario on important services and objectives."},
    {"information_id": "critical_services_and_objectives", "consumer_subcategory_id": "PR.IR-03", "dependency_kind": "planning_input", "use_reason": "Set resilience requirements for normal and adverse situations."},
    {"information_id": "critical_services_and_objectives", "consumer_subcategory_id": "RC.RP-02", "dependency_kind": "required_input", "use_reason": "Select and prioritize recovery actions according to the services and objectives that need restoration."},
    {"information_id": "critical_services_and_objectives", "consumer_subcategory_id": "RC.RP-04", "dependency_kind": "required_input", "use_reason": "Establish post-incident operating norms using critical mission functions and services."},
    {"information_id": "critical_services_and_objectives", "consumer_subcategory_id": "RC.CO-03", "dependency_kind": "planning_input", "use_reason": "Explain recovery progress for capabilities that stakeholders depend on."},

    {"information_id": "external_dependencies", "consumer_subcategory_id": "ID.AM-04", "dependency_kind": "planning_input", "use_reason": "Maintain an inventory of supplier-provided services that the organization depends on."},
    {"information_id": "external_dependencies", "consumer_subcategory_id": "GV.SC-04", "dependency_kind": "planning_input", "use_reason": "Identify and prioritize suppliers by the importance of the dependency they provide."},
    {"information_id": "external_dependencies", "consumer_subcategory_id": "ID.RA-10", "dependency_kind": "planning_input", "use_reason": "Identify which suppliers are critical enough to assess before acquisition."},
    {"information_id": "external_dependencies", "consumer_subcategory_id": "DE.CM-06", "dependency_kind": "planning_input", "use_reason": "Decide which external services and providers need monitoring for potentially adverse events."},
    {"information_id": "external_dependencies", "consumer_subcategory_id": "RC.RP-02", "dependency_kind": "planning_input", "use_reason": "Account for provider and service dependencies when selecting recovery actions."},

    {"information_id": "risk_objectives_and_tolerance", "consumer_subcategory_id": "GV.PO-01", "dependency_kind": "planning_input", "use_reason": "Align cybersecurity policy with agreed risk objectives, tolerance, and response direction."},
    {"information_id": "risk_objectives_and_tolerance", "consumer_subcategory_id": "ID.RA-06", "dependency_kind": "planning_input", "use_reason": "Choose and prioritize risk responses that fit agreed risk direction and tolerance."},
    {"information_id": "risk_objectives_and_tolerance", "consumer_subcategory_id": "GV.RR-03", "dependency_kind": "planning_input", "use_reason": "Allocate resources in line with the cybersecurity risk strategy and priorities."},
    {"information_id": "risk_assessment_method", "consumer_subcategory_id": "ID.RA-04", "dependency_kind": "required_input", "use_reason": "Use the established method to calculate and record likelihood and impact."},
    {"information_id": "risk_assessment_method", "consumer_subcategory_id": "ID.RA-05", "dependency_kind": "required_input", "use_reason": "Use the established method to understand inherent risk and prioritize responses consistently."},
    {"information_id": "risk_assessment_method", "consumer_subcategory_id": "ID.RA-06", "dependency_kind": "planning_input", "use_reason": "Use the established method when selecting, tracking, and communicating risk responses."},
    {"information_id": "risk_assessment_method", "consumer_subcategory_id": "ID.RA-07", "dependency_kind": "required_input", "use_reason": "Use the established method to assess and record the risk impact of proposed changes and requested exceptions."},
    {"information_id": "cybersecurity_roles", "consumer_subcategory_id": "GV.SC-02", "dependency_kind": "required_input", "use_reason": "Coordinate supplier, customer, partner, and internal cybersecurity responsibilities."},
    {"information_id": "cybersecurity_roles", "consumer_subcategory_id": "RS.MA-01", "dependency_kind": "required_input", "use_reason": "Execute the incident response plan with the people and third parties who have assigned responsibilities."},
    {"information_id": "cybersecurity_roles", "consumer_subcategory_id": "RC.RP-01", "dependency_kind": "required_input", "use_reason": "Execute recovery work with people who have the necessary responsibilities and authorizations."},

    {"information_id": "supplier_criticality", "consumer_subcategory_id": "GV.SC-05", "dependency_kind": "planning_input", "use_reason": "Prioritize supplier requirements according to the importance of the supplier or service."},
    {"information_id": "supplier_criticality", "consumer_subcategory_id": "GV.SC-06", "dependency_kind": "planning_input", "use_reason": "Focus pre-relationship planning and due diligence on suppliers that matter most."},
    {"information_id": "supplier_criticality", "consumer_subcategory_id": "ID.RA-10", "dependency_kind": "required_input", "use_reason": "Determine which suppliers are critical and must be assessed before acquisition."},
    {"information_id": "supplier_criticality", "consumer_subcategory_id": "GV.SC-07", "dependency_kind": "planning_input", "use_reason": "Prioritize supplier risk assessment and monitoring over the relationship lifecycle."},
    {"information_id": "asset_inventory", "consumer_subcategory_id": "ID.RA-01", "dependency_kind": "required_input", "use_reason": "Identify the managed assets whose vulnerabilities must be found, validated, and recorded."},
    {"information_id": "asset_inventory", "consumer_subcategory_id": "ID.RA-09", "dependency_kind": "required_input", "use_reason": "Identify acquired hardware and software whose authenticity and integrity must be assessed."},
    {"information_id": "asset_inventory", "consumer_subcategory_id": "PR.PS-01", "dependency_kind": "required_input", "use_reason": "Apply configuration management to known platforms and software."},
    {"information_id": "asset_inventory", "consumer_subcategory_id": "PR.PS-02", "dependency_kind": "required_input", "use_reason": "Maintain, replace, and remove known software commensurate with risk."},
    {"information_id": "asset_inventory", "consumer_subcategory_id": "PR.PS-03", "dependency_kind": "required_input", "use_reason": "Maintain, replace, and remove known hardware commensurate with risk."},
    {"information_id": "asset_inventory", "consumer_subcategory_id": "DE.CM-09", "dependency_kind": "required_input", "use_reason": "Monitor known computing hardware, software, runtime environments, and their data."},
    {"information_id": "network_and_data_flows", "consumer_subcategory_id": "PR.DS-02", "dependency_kind": "planning_input", "use_reason": "Protect data in transit based on how and where it moves."},
    {"information_id": "network_and_data_flows", "consumer_subcategory_id": "PR.IR-01", "dependency_kind": "planning_input", "use_reason": "Protect networks and environments according to authorized communication paths."},
    {"information_id": "network_and_data_flows", "consumer_subcategory_id": "DE.CM-01", "dependency_kind": "required_input", "use_reason": "Monitor networks and network services that are known to carry authorized communication."},
    {"information_id": "asset_criticality", "consumer_subcategory_id": "ID.RA-04", "dependency_kind": "planning_input", "use_reason": "Estimate impact using the importance of affected assets and services."},
    {"information_id": "asset_criticality", "consumer_subcategory_id": "RC.RP-02", "dependency_kind": "planning_input", "use_reason": "Prioritize recovery actions according to asset and service importance."},

    {"information_id": "vulnerabilities_and_threats", "consumer_subcategory_id": "ID.RA-04", "dependency_kind": "required_input", "use_reason": "Evaluate the likelihood and impact of threats exploiting known vulnerabilities."},
    {"information_id": "vulnerabilities_and_threats", "consumer_subcategory_id": "ID.RA-05", "dependency_kind": "required_input", "use_reason": "Understand inherent risk from recorded threats, vulnerabilities, likelihoods, and impacts."},
    {"information_id": "risk_scenarios_and_priorities", "consumer_subcategory_id": "ID.RA-06", "dependency_kind": "required_input", "use_reason": "Choose, prioritize, plan, track, and communicate risk responses for recorded risks."},
    {"information_id": "change_and_exception_risk_records", "consumer_subcategory_id": "ID.RA-06", "dependency_kind": "planning_input", "use_reason": "Use documented change and exception risks when selecting, planning, tracking, and communicating their responses."},
    {"information_id": "secure_development_performance_results", "consumer_subcategory_id": "ID.IM-01", "dependency_kind": "planning_input", "use_reason": "Evaluate secure-development performance results to identify software-development practices that need improvement."},
    {"information_id": "authorized_adverse_event_alerts", "consumer_subcategory_id": "DE.AE-08", "dependency_kind": "event_input", "use_reason": "Provide authorized decision-makers and tools the adverse-event information used to apply incident declaration criteria."},
    {"information_id": "authorized_adverse_event_alerts", "consumer_subcategory_id": "RS.MA-02", "dependency_kind": "event_input", "use_reason": "Provide responders and triage tools the alerts, findings, and tickets used to validate incident reports."},
    {"information_id": "selected_risk_responses", "consumer_subcategory_id": "PR.AA-05", "dependency_kind": "planning_input", "use_reason": "Apply access permissions and reviews in accordance with chosen risk responses."},
    {"information_id": "selected_risk_responses", "consumer_subcategory_id": "PR.DS-01", "dependency_kind": "planning_input", "use_reason": "Select protections for data at rest that fit the chosen response to risk."},
    {"information_id": "selected_risk_responses", "consumer_subcategory_id": "PR.DS-02", "dependency_kind": "planning_input", "use_reason": "Select protections for data in transit that fit the chosen response to risk."},
    {"information_id": "selected_risk_responses", "consumer_subcategory_id": "PR.DS-10", "dependency_kind": "planning_input", "use_reason": "Select protections for data in use that fit the chosen response to risk."},
    {"information_id": "selected_risk_responses", "consumer_subcategory_id": "PR.IR-03", "dependency_kind": "planning_input", "use_reason": "Implement resilience mechanisms that fit selected risk responses."},

    {"information_id": "monitoring_findings", "consumer_subcategory_id": "DE.AE-02", "dependency_kind": "event_input", "use_reason": "Analyze potentially adverse events to understand the associated activity."},
    {"information_id": "monitoring_findings", "consumer_subcategory_id": "DE.AE-03", "dependency_kind": "event_input", "use_reason": "Correlate information from multiple sources when investigating potentially adverse events."},
    {"information_id": "monitoring_findings", "consumer_subcategory_id": "DE.AE-04", "dependency_kind": "event_input", "use_reason": "Estimate the impact and scope of potentially adverse events."},
    {"information_id": "monitoring_findings", "consumer_subcategory_id": "DE.AE-08", "dependency_kind": "event_input", "use_reason": "Apply incident criteria to analyzed potentially adverse events."},
    {"information_id": "incident_analysis", "consumer_subcategory_id": "RS.MA-01", "dependency_kind": "event_input", "use_reason": "Execute the response plan once an incident is declared and its situation is understood."},
    {"information_id": "incident_analysis", "consumer_subcategory_id": "RS.MA-03", "dependency_kind": "event_input", "use_reason": "Categorize and prioritize incidents using investigation results, scope, and impact."},
    {"information_id": "incident_analysis", "consumer_subcategory_id": "RS.MI-01", "dependency_kind": "event_input", "use_reason": "Contain an incident using the available analysis of what happened and what is affected."},
    {"information_id": "incident_analysis", "consumer_subcategory_id": "RS.MI-02", "dependency_kind": "event_input", "use_reason": "Eradicate the incident using investigation and root-cause information."},
    {"information_id": "incident_analysis", "consumer_subcategory_id": "RC.RP-01", "dependency_kind": "event_input", "use_reason": "Initiate and execute the recovery portion of the response plan when incident response calls for it."},
    {"information_id": "recovery_priorities_and_status", "consumer_subcategory_id": "RC.RP-05", "dependency_kind": "event_input", "use_reason": "Verify integrity, restore systems and services, and confirm normal operating status."},
    {"information_id": "recovery_priorities_and_status", "consumer_subcategory_id": "RC.RP-06", "dependency_kind": "event_input", "use_reason": "Declare recovery complete using restoration criteria and complete incident-related documentation."},
    {"information_id": "recovery_priorities_and_status", "consumer_subcategory_id": "RC.CO-03", "dependency_kind": "event_input", "use_reason": "Communicate recovery activities and restoration progress to designated stakeholders."},
    {"information_id": "improvement_lessons", "consumer_subcategory_id": "GV.OV-01", "dependency_kind": "planning_input", "use_reason": "Review risk-management outcomes and adjust strategy and direction when needed."},
    {"information_id": "improvement_lessons", "consumer_subcategory_id": "GV.OV-02", "dependency_kind": "planning_input", "use_reason": "Review and adjust the strategy to cover organizational requirements and risks."},
    {"information_id": "improvement_lessons", "consumer_subcategory_id": "GV.PO-02", "dependency_kind": "planning_input", "use_reason": "Update policy to reflect changes, findings, and lessons learned."},
    {"information_id": "improvement_lessons", "consumer_subcategory_id": "ID.IM-04", "dependency_kind": "planning_input", "use_reason": "Maintain and improve incident response and other cybersecurity plans that affect operations."},

    # Proposed product-authored dependency pass: these links make explicit
    # handoffs that the CSF outcomes imply but do not sequence for the user.
    {"information_id": "risk_objectives_and_tolerance", "consumer_subcategory_id": "GV.RM-03", "dependency_kind": "planning_input", "use_reason": "Bring agreed cybersecurity risk objectives, tolerance, and response direction into enterprise risk management."},
    {"information_id": "risk_scenarios_and_priorities", "consumer_subcategory_id": "GV.RM-03", "dependency_kind": "planning_input", "use_reason": "Represent analyzed cybersecurity risks in enterprise risk management processes."},
    {"information_id": "selected_risk_responses", "consumer_subcategory_id": "GV.RM-03", "dependency_kind": "planning_input", "use_reason": "Coordinate selected cybersecurity risk responses with enterprise risk decisions."},
    {"information_id": "risk_objectives_and_tolerance", "consumer_subcategory_id": "GV.RM-07", "dependency_kind": "planning_input", "use_reason": "Consider positive cybersecurity opportunities against agreed risk objectives and tolerance."},
    {"information_id": "risk_scenarios_and_priorities", "consumer_subcategory_id": "GV.RM-07", "dependency_kind": "planning_input", "use_reason": "Use risk analysis to identify potential beneficial opportunities."},
    {"information_id": "risk_management_measures_and_results", "consumer_subcategory_id": "GV.OV-03", "dependency_kind": "planning_input", "use_reason": "Use agreed KPIs, KRIs, and thresholds to judge cybersecurity risk-management performance consistently."},
    {"information_id": "risk_management_performance_results", "consumer_subcategory_id": "GV.OV-03", "dependency_kind": "required_input", "use_reason": "Review actual measurement and evidence results to determine whether cybersecurity risk management needs adjustment."},
    {"information_id": "risk_management_review_findings", "consumer_subcategory_id": "GV.OV-01", "dependency_kind": "planning_input", "use_reason": "Use performance-review findings when reviewing strategy outcomes and adjusting direction."},
    {"information_id": "risk_management_review_findings", "consumer_subcategory_id": "GV.OV-02", "dependency_kind": "planning_input", "use_reason": "Use performance-review findings when adjusting the strategy to cover organizational requirements and risks."},
    {"information_id": "risk_management_review_findings", "consumer_subcategory_id": "GV.PO-02", "dependency_kind": "planning_input", "use_reason": "Use performance-review findings when deciding whether cybersecurity policy needs updating."},
    {"information_id": "supply_chain_program_direction", "consumer_subcategory_id": "GV.SC-03", "dependency_kind": "required_input", "use_reason": "Integrate the established supply-chain risk program, strategy, objectives, policies, and processes with cybersecurity and enterprise risk work."},
    {"information_id": "supplier_lifecycle_results", "consumer_subcategory_id": "GV.SC-03", "dependency_kind": "required_input", "use_reason": "Bring recorded supplier and supply-chain risks into cybersecurity, enterprise risk, assessment, and improvement processes."},
    {"information_id": "integrated_supply_chain_risk_records", "consumer_subcategory_id": "GV.RM-03", "dependency_kind": "planning_input", "use_reason": "Escalate and address material supply-chain risks through enterprise risk management processes."},
    {"information_id": "external_legal_contractual_sources", "consumer_subcategory_id": "GV.OC-03", "dependency_kind": "required_input", "use_reason": "Identify and manage the external legal, regulatory, contractual, privacy, and civil-liberties requirements that constrain cybersecurity decisions."},
    {"information_id": "cybersecurity_roles", "consumer_subcategory_id": "GV.SC-08", "dependency_kind": "required_input", "use_reason": "Identify the supplier and internal roles that must participate in incident planning, response, and recovery."},
    {"information_id": "supplier_requirements_and_agreements", "consumer_subcategory_id": "GV.SC-08", "dependency_kind": "planning_input", "use_reason": "Use supplier agreement responsibilities when planning supplier incident involvement."},
    {"information_id": "incident_response_plan", "consumer_subcategory_id": "GV.SC-08", "dependency_kind": "planning_input", "use_reason": "Include relevant suppliers and other third parties in the incident response plan and recovery coordination."},
    {"information_id": "supply_chain_program_direction", "consumer_subcategory_id": "GV.SC-09", "dependency_kind": "planning_input", "use_reason": "Apply the agreed supply-chain program direction throughout the technology and service life cycle."},
    {"information_id": "supplier_criticality", "consumer_subcategory_id": "GV.SC-09", "dependency_kind": "planning_input", "use_reason": "Focus life-cycle practices and review effort on suppliers and services that matter most."},
    {"information_id": "supplier_lifecycle_results", "consumer_subcategory_id": "GV.SC-09", "dependency_kind": "planning_input", "use_reason": "Use supplier assessment and monitoring results to evaluate supply-chain practice performance."},
    {"information_id": "external_dependencies", "consumer_subcategory_id": "GV.SC-10", "dependency_kind": "planning_input", "use_reason": "Plan for the dependencies that must be transitioned, replaced, or ended after a supplier relationship concludes."},
    {"information_id": "supplier_requirements_and_agreements", "consumer_subcategory_id": "GV.SC-10", "dependency_kind": "planning_input", "use_reason": "Use agreement terms to identify post-relationship cybersecurity obligations and handoffs."},
    {"information_id": "asset_inventory", "consumer_subcategory_id": "GV.SC-10", "dependency_kind": "planning_input", "use_reason": "Identify supplier-provided services and related assets that must be transitioned or retired."},
    {"information_id": "asset_inventory", "consumer_subcategory_id": "ID.AM-08", "dependency_kind": "required_input", "use_reason": "Manage known hardware, software, services, and data through their life cycles."},
    {"information_id": "asset_criticality", "consumer_subcategory_id": "ID.AM-08", "dependency_kind": "planning_input", "use_reason": "Apply life-cycle attention and resources according to asset importance and impact."},
    {"information_id": "threat_intelligence", "consumer_subcategory_id": "ID.RA-03", "dependency_kind": "planning_input", "use_reason": "Identify and record internal and external threats relevant to the organization."},
    {"information_id": "threat_intelligence", "consumer_subcategory_id": "ID.RA-04", "dependency_kind": "planning_input", "use_reason": "Use relevant threat information when estimating likelihood and impact."},
    {"information_id": "threat_intelligence", "consumer_subcategory_id": "DE.AE-07", "dependency_kind": "event_input", "use_reason": "Apply relevant threat intelligence as context during potentially adverse event analysis."},
    {"information_id": "external_vulnerability_disclosures", "consumer_subcategory_id": "ID.RA-08", "dependency_kind": "event_input", "use_reason": "Receive, analyze, and respond to vulnerability disclosures from external sources."},
    {"information_id": "vulnerabilities_and_threats", "consumer_subcategory_id": "ID.RA-01", "dependency_kind": "planning_input", "use_reason": "Validate and record vulnerabilities identified through the disclosure process and other sources."},
    {"information_id": "restoration_assets", "consumer_subcategory_id": "RC.RP-03", "dependency_kind": "event_input", "use_reason": "Verify the integrity of backups and restoration assets before using them for restoration."},
    {"information_id": "verified_restoration_assets", "consumer_subcategory_id": "RC.RP-05", "dependency_kind": "event_input", "use_reason": "Use verified restoration assets to restore systems and services and confirm normal operation."},
    {"information_id": "log_records", "consumer_subcategory_id": "DE.CM-09", "dependency_kind": "required_input", "use_reason": "Make log records available for monitoring of computing hardware, software, runtime environments, and data."},
    {"information_id": "event_threat_context", "consumer_subcategory_id": "DE.AE-02", "dependency_kind": "event_input", "use_reason": "Use threat context to better understand potentially adverse events and associated activity."},
    {"information_id": "event_threat_context", "consumer_subcategory_id": "DE.AE-04", "dependency_kind": "event_input", "use_reason": "Use threat context when estimating the impact and scope of potentially adverse events."},
    {"information_id": "analyzed_event_information", "consumer_subcategory_id": "RS.MA-02", "dependency_kind": "event_input", "use_reason": "Triage and validate incident reports using analyzed event activity, impact, scope, and incident criteria."},
    {"information_id": "triaged_incident_reports", "consumer_subcategory_id": "RS.MA-03", "dependency_kind": "event_input", "use_reason": "Categorize and prioritize validated incident reports."},
    {"information_id": "incident_priority_and_scope", "consumer_subcategory_id": "RS.MA-04", "dependency_kind": "event_input", "use_reason": "Escalate incidents using their established priority, magnitude, scope, and impact."},
    {"information_id": "incident_priority_and_scope", "consumer_subcategory_id": "RS.MA-05", "dependency_kind": "event_input", "use_reason": "Apply recovery-initiation criteria using the prioritized incident and its validated scope."},
    {"information_id": "recovery_initiation_decision", "consumer_subcategory_id": "RC.RP-01", "dependency_kind": "event_input", "use_reason": "Execute the recovery portion of the incident response plan once recovery is initiated."},
    {"information_id": "incident_analysis", "consumer_subcategory_id": "RS.AN-06", "dependency_kind": "event_input", "use_reason": "Record investigation actions and preserve their integrity and provenance."},
    {"information_id": "incident_analysis", "consumer_subcategory_id": "RS.AN-07", "dependency_kind": "event_input", "use_reason": "Collect incident data and metadata and preserve their integrity and provenance."},
    {"information_id": "preserved_investigation_records", "consumer_subcategory_id": "RS.AN-07", "dependency_kind": "event_input", "use_reason": "Carry preserved investigation actions and records into the complete incident data record."},
    {"information_id": "incident_analysis", "consumer_subcategory_id": "RS.AN-08", "dependency_kind": "event_input", "use_reason": "Use incident investigation and preserved data to estimate and validate incident magnitude."},
]
